language: smalltalk
sudo: true

install:
  - [ "$TRAVIS_OS_NAME" = "osx" ] && sudo easy_install pip
  - pip install --user benchupload
  - [ "$TRAVIS_OS_NAME" = "osx" ] && export unset DISCORD_ST_TEST_CASE_BOT_TOKEN

os:
  - linux
  - osx

smalltalk:
  - Pharo-6.1

# bob-bench xUnit file analysis
after_success:
  - benchupload --dir=$SMALLTALK_CI_BUILD
after_failure:
  - benchupload --dir=$SMALLTALK_CI_BUILD
