language: smalltalk
sudo: false

install:
  - pip install --user benchupload

os:
  - linux
  - osx

smalltalk:
  - Pharo-6.0

# bob-bench xUnit file analysis
after_success:
  - benchupload --dir=$SMALLTALK_CI_BUILD
after_failure:
  - benchupload --dir=$SMALLTALK_CI_BUILD

notifications:
  discord:
    channels:
      - [$CESTA_TRAVIS_CI_WEBHOOK_ID]:[$CESTA_TRAVIS_CI_WEBHOOK_TOKEN]
    pull_request_template:
      - 'Build [#%{build_number}](%{build_url}) ([%{commit}](%{compare_url})) of %{repository}@%{branch} in PR [#%{pull_request_number}](%{pull_request_url}) by %{author} %{result} in %{duration}'
    branch_template:
      - 'Build [#%{build_number}](%{build_url}) ([%{commit}](%{compare_url})) of %{repository}@%{branch} by %{author} %{result} in %{duration}'
